### ISSUE TITLE
Ideas for refactor

### ISSUE THREAD

**Issue by franalbani** [karpatkey/defyes#19]
Please edit this when you have a new idea.

# Ideas

- [x] avoid `import *` #23 
- [x] #18
- properly handle config parameters 
- [x] don't loose precision in decimals: #50 
- make use of apeworx to interact with blockchain (apeworx.io)
- [x] make databases for contractaddresses and their ABIs (no ABI constants)
- make "block='latest'" an optional argument whenever possible, e.g. for the underlying functions
- try to get "basic" contract data with one API call (decimals, etc.)

## Tidiness 

- [x] move all protocols to `defi-protocols/protocols`
- [x] use multiple lines for ABI and not one (if we keep ABI constants)
- [x] #55
- decouple "finance calculus" code from "API calls" code, move it to something like `defi-protocols/finance.py` and test it independently. 

## Typing

- make all protocols inherit from a common class.
- make custom types for token, contract, web3 and more
- put results in dict and not list
- make more use of dataclasses instead of functions and classes
- Creating the "address" data type would help the readability of the code through type hinting.
- We should consider adding a "types" directory and consider other potentially useful types.
- make custom class for converting balances without decimals to with decimals

### Candidates

* Token
  * E.g.: DAI, ETH, etc.
* Address
* Blockchain
  * E.g.: XDAI, ETHEREUM
* Contract
* Balance: e.g.: abstract decimals stuff

# Observations

* the same protocol may be deployed in many blockchains

**Comment by ph1t0** [comment]
* properly handle config parameters

**Comment by sgzerbo** [comment]
- make "block='latest'" an optional argument whenever possible, e.g. for the underlying functions

**Comment by sgzerbo** [comment]
Creating the "address" data type would help the readability of the code through type hinting.

We should consider adding a "types" directory and consider other potentially useful types.

**Comment by franalbani** [comment]
```python
Class BalanceItem:
   token: str
   decimals: int
   raw_amount: int
   def human_readable(self):
       return "la cuentita"
```
