### ISSUE TITLE
Invalid API Key for date_to_block("2024-03-01 00:00:00", "base")

### ISSUE THREAD

**Issue by ubabe53** [karpatkey/defyes#385]
date_to_block works with almost all dates expect for this one just on base. 
trying to run: 

    
    from defyes.functions import date_to_block
    x = date_to_block("2024-03-01 00:00:00", "base")
    print(x)
    

will result in a string:  "Invalid API Key"

**Comment by sgzerbo** [comment]
Works locally for me. We were missing the APIKEYS_BASESCAN secret in the repo, that might be the reason... I just added it
<img width="148" alt="image" src="https://github.com/karpatkey/defyes/assets/98768518/530a1e03-17e8-43c3-a68e-dc3c83dfc15f">
